import Navbar from "@/components/system/Navbar";
import "./globals.css";
import { DM_Sans } from "next/font/google";
import { ThemeProviderMafia } from "@/components/providers/theme-provider";

const dM_Sans = DM_Sans({
  weights: ["100", "200", "300", "400", "500", "600", "800", "900", "1000"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Meta Mafia - Automated SEO Metadata for Next.js 14",
  description:
    "Meta Mafia empowers developers to easily generate SEO-optimized metadata code for Next.js 14 websites. Just input your website data, and let AI handle the rest!",
  keywords:
    "SEO, metadata generation, Next.js 14, Meta Mafia, SEO tools, automated SEO, website optimization, OpenAI API",
  author: "Meta Mafia Team",
  robots: "index, follow",
  openGraph: {
    type: "website",
    url: "https://metamafia.dev",
    title: "Meta Mafia - Automated SEO Metadata for Next.js",
    description:
      "Streamline SEO metadata creation for Next.js websites with Meta Mafia. Input your data, and get SEO-friendly metadata code generated by AI.",
    images: [
      {
        url: "/logo.png",
        width: 1200,
        height: 630,
        alt: "Meta Mafia - Automated SEO Metadata",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dM_Sans.className}>
        <ThemeProviderMafia
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <Navbar />
          {children}
        </ThemeProviderMafia>
      </body>
    </html>
  );
}
