import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/system/navbar";
import { ThemeProvider } from "@/providers/theme-provider";

const dM_Sans = DM_Sans({
  weights: ["100", "200", "300", "400", "500", "600", "800", "900", "1000"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Meta Mafia - Automated SEO Metadata for Next.js website",
  description:
    "Meta Mafia empowers developers to easily generate SEO-optimized metadata code for Next.js project websites. Just input your website data, and let AI handle the rest!",
  keywords:
    "SEO, metadata generation, Next.js project, Meta Mafia, SEO tools, automated SEO, website optimization, OpenAI API",
  author: "Meta Mafia Team",
  robots: "index, follow",
  openGraph: {
    type: "website",
    url: "https://metamafia.dev",
    title: "Meta Mafia - Automated SEO Metadata for Next.js",
    description:
      "Streamline SEO metadata creation for Next.js websites with Meta Mafia. Input your data, and get SEO-friendly metadata code generated by AI.",
    images: [
      {
        url: "/logo.png",
        width: 1200,
        height: 630,
        alt: "Meta Mafia - Automated SEO Metadata",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${dM_Sans.className} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
